var annotated =
[
    [ "ABP_10x_t", "struct_a_b_p__10x__t.html", "struct_a_b_p__10x__t" ],
    [ "arr16b_t", "structarr16b__t.html", "structarr16b__t" ],
    [ "arr8b_t", "structarr8b__t.html", "structarr8b__t" ],
    [ "chipStatus_t", "unionchip_status__t.html", "unionchip_status__t" ],
    [ "coreArguments_t", "structcore_arguments__t.html", "structcore_arguments__t" ],
    [ "coreConfiguration_t", "unioncore_configuration__t.html", "unioncore_configuration__t" ],
    [ "coreInfo_t", "structcore_info__t.html", "structcore_info__t" ],
    [ "coreStatus_t", "structcore_status__t.html", "structcore_status__t" ],
    [ "deviceErrors_t", "uniondevice_errors__t.html", "uniondevice_errors__t" ],
    [ "errorStatus_t", "unionerror_status__t.html", "unionerror_status__t" ],
    [ "FSKModulationParams_t", "struct_f_s_k_modulation_params__t.html", "struct_f_s_k_modulation_params__t" ],
    [ "FSKPacketParams_t", "struct_f_s_k_packet_params__t.html", "struct_f_s_k_packet_params__t" ],
    [ "ipc_msg_t", "structipc__msg__t.html", "structipc__msg__t" ],
    [ "ipc_msgs_t", "structipc__msgs__t.html", "structipc__msgs__t" ],
    [ "IRQstatus_t", "union_i_r_qstatus__t.html", "union_i_r_qstatus__t" ],
    [ "LoRaModulationParams_t", "struct_lo_ra_modulation_params__t.html", "struct_lo_ra_modulation_params__t" ],
    [ "LoRaPacketParams_t", "struct_lo_ra_packet_params__t.html", "struct_lo_ra_packet_params__t" ],
    [ "LoRaPacketStatus_t", "union_lo_ra_packet_status__t.html", "union_lo_ra_packet_status__t" ],
    [ "LoRaStats_t", "struct_lo_ra_stats__t.html", "struct_lo_ra_stats__t" ],
    [ "LoRaWAN_keys_t", "struct_lo_ra_w_a_n__keys__t.html", "struct_lo_ra_w_a_n__keys__t" ],
    [ "macStatus_t", "unionmac_status__t.html", "unionmac_status__t" ],
    [ "OTAA_10x_t", "struct_o_t_a_a__10x__t.html", "struct_o_t_a_a__10x__t" ],
    [ "OTAA_11x_t", "struct_o_t_a_a__11x__t.html", "struct_o_t_a_a__11x__t" ],
    [ "parameterStatus_t", "unionparameter_status__t.html", "unionparameter_status__t" ],
    [ "QTstyle_Test", "class_q_tstyle___test.html", "class_q_tstyle___test" ],
    [ "RadioParams_t", "struct_radio_params__t.html", "struct_radio_params__t" ],
    [ "radioStatus_t", "unionradio_status__t.html", "unionradio_status__t" ],
    [ "RadioStatus_t", "struct_radio_status__t.html", "struct_radio_status__t" ],
    [ "sleepConfig_t", "structsleep_config__t.html", "structsleep_config__t" ],
    [ "StoredKeys_t", "struct_stored_keys__t.html", "struct_stored_keys__t" ],
    [ "systemStatus_t", "unionsystem_status__t.html", "unionsystem_status__t" ],
    [ "TX", "struct_t_x.html", null ],
    [ "wakeUpPin_t", "structwake_up_pin__t.html", "structwake_up_pin__t" ],
    [ "wakeUpTime_t", "structwake_up_time__t.html", "structwake_up_time__t" ]
];