.TH "_getting" 3 "Thu Jan 7 2021" "LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_getting \- Started 

.SS "Installing the IDE"
To get started with Onethinx LoRaWAN module, you need an IDE\&. We have developed our own IDE based around Visual Studio Code\&.
.PP
\fCWindows\fP
.SS "Installing the IDE"
Text 1234567890
.SS "Installing the IDE"
.IP "\(bu" 2
Text 1234567890
.PP
.SS "Using the correct API libraries"
.IP "\(bu" 2
Text 1234567890
.PP
.SS "Datasheet and CAD libraries"
.IP "\(bu" 2
Text 1234567890 etc\&.\&.\&. 
.PP

