.TH "ABP_10x_t" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ABP_10x_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OnethinxCore01\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBarr8b_t\fP \fBDevEui\fP"
.br
.ti -1c
.RI "uint32_t \fBDevAddr\fP"
.br
.ti -1c
.RI "\fBarr16b_t\fP \fBNwkSkey\fP"
.br
.ti -1c
.RI "\fBarr16b_t\fP \fBAppSkey\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBarr16b_t\fP AppSkey"

.SS "uint32_t DevAddr"

.SS "\fBarr8b_t\fP DevEui"

.SS "\fBarr16b_t\fP NwkSkey"


.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
