.TH "advanced" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
advanced \- Advanced 

.SH "Structures"
.PP
.SS "LoRaWAN configuration"
TODO 
.SS "LoRaWAN status"
TODO 
.SS "LoRa configuration"
TODO 
.SS "LoRa status"
TODO 
.SH "Module Versions"
.PP
.SS "EU868"
TODO 
.SS "US915"
TODO 
.SS "AU923"
Not yet available\&. 
.SS "IN865"
Not yet available\&. 
.SH "Pinout"
.PP
TODO 
.SH "Footprint"
.PP
TODO 
.SH "Internal DevEUI"
.PP
TODO UART OpenOCD OTX18-Programmer 
.SH "OpenOCD Programming"
.PP
TODO 
