.TH "chipStatus_t" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
chipStatus_t \- Represents the possible device error states\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OnethinxExt01\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBValue\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint8_t \fB__pad0__\fP: 1"
.br
.RI "Reserved\&. "
.ti -1c
.RI "   uint8_t \fBCmdStatus\fP: 3"
.br
.RI "Command status\&. "
.ti -1c
.RI "   uint8_t \fBChipMode\fP: 3"
.br
.RI "Chip mode\&. "
.ti -1c
.RI "   uint8_t \fBCpuBusy\fP: 1"
.br
.RI "Flag for CPU radio busy\&. "
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents the possible device error states\&. 
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint8_t __pad0__"

.PP
Reserved\&. 
.SS "uint8_t ChipMode"

.PP
Chip mode\&. 
.SS "uint8_t CmdStatus"

.PP
Command status\&. 
.SS "uint8_t CpuBusy"

.PP
Flag for CPU radio busy\&. 
.SS "uint8_t Value"


.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
