.TH "coreStatus_t" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
coreStatus_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OnethinxCore01\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBparameterStatus_t\fP \fBparameters\fP"
.br
.ti -1c
.RI "\fBradioStatus_t\fP \fBradio\fP"
.br
.ti -1c
.RI "\fBmacStatus_t\fP \fBmac\fP"
.br
.ti -1c
.RI "\fBsystemStatus_t\fP \fBsystem\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBmacStatus_t\fP mac"

.SS "\fBparameterStatus_t\fP parameters"

.SS "\fBradioStatus_t\fP radio"

.SS "\fBsystemStatus_t\fP system"


.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
