.TH "errorStatus_t" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
errorStatus_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OnethinxCore01\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBerrorValue\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBparamErrors_e\fP \fBparamErrors\fP: 8"
.br
.ti -1c
.RI "   \fBradioErrors_e\fP \fBradioErrors\fP: 8"
.br
.ti -1c
.RI "   \fBmacErrors_e\fP \fBmacErrors\fP: 8"
.br
.ti -1c
.RI "   \fBsystemErrors_e\fP \fBsystemErrors\fP: 8"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint32_t errorValue"

.SS "\fBmacErrors_e\fP macErrors"

.SS "\fBparamErrors_e\fP paramErrors"

.SS "\fBradioErrors_e\fP radioErrors"

.SS "\fBsystemErrors_e\fP systemErrors"


.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
