.TH "extra_resources" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
extra_resources \- Extra Resources 

.SH "Structures"
.PP
.SS "LoRaWAN configuration"
TODO 
.SS "LoRaWAN status"
TODO 
.SS "LoRa configuration"
TODO 
.SS "LoRa status"
TODO 
.SH "Module Versions"
.PP
.SS "EU868"
In production and available\&. CE and LoRa Alliance certified\&. 
.SS "US915"
In production and available\&. FCC certified\&. 
.SS "AU923"
Not yet available\&. Close to release\&. 
.SS "IN865"
Not available\&. 
.SH "Pinout"
.PP
TODO 
.SH "Footprint"
.PP
TODO 
.SH "Internal DevEUI"
.PP
TODO UART OpenOCD OTX18-Programmer 
.SH "OpenOCD Programming"
.PP
TODO 
