.TH "FSKModulationParams_t" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FSKModulationParams_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OnethinxExt01\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBRadioFSKRBitrate_e\fP \fBBitRate\fP: 32"
.br
.ti -1c
.RI "\fBRadioFSKRDeviation_e\fP \fBFdev\fP: 32"
.br
.ti -1c
.RI "\fBRadioFSKModShapings_e\fP \fBPulseShape\fP: 8"
.br
.ti -1c
.RI "\fBRadioFSKRxBandwidth_e\fP \fBRxBandwidth\fP: 8"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBRadioFSKRBitrate_e\fP BitRate"

.SS "\fBRadioFSKRDeviation_e\fP Fdev"

.SS "\fBRadioFSKModShapings_e\fP PulseShape"

.SS "\fBRadioFSKRxBandwidth_e\fP RxBandwidth"


.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
