.TH "ipc_msg_t" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ipc_msg_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OnethinxCore01\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint8_t \fBclientId\fP"
.br
.ti -1c
.RI "uint8_t \fBuserCode\fP"
.br
.ti -1c
.RI "uint16_t \fBintrMask\fP"
.br
.ti -1c
.RI "volatile void * \fBcoreArgumentsPtr\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint8_t clientId"

.SS "volatile void* coreArgumentsPtr"

.SS "uint16_t intrMask"

.SS "uint8_t userCode"


.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
