.TH "lora_structs_lora" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lora_structs_lora \- LoRa
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "union \fBLoRaPacketStatus_t\fP"
.br
.RI "Represents the packet status for every packet type\&. "
.ti -1c
.RI "struct \fBLoRaStats_t\fP"
.br
.RI "Represents the LoRa Packet statistics\&. "
.ti -1c
.RI "struct \fBLoRaModulationParams_t\fP"
.br
.ti -1c
.RI "struct \fBLoRaPacketParams_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
