.TH "lora_structs_general" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lora_structs_general \- General
.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBRadioParams_t\fP"
.br
.ti -1c
.RI "union \fBchipStatus_t\fP"
.br
.RI "Represents the possible device error states\&. "
.ti -1c
.RI "union \fBIRQstatus_t\fP"
.br
.RI "Represents the possible IRQ states\&. "
.ti -1c
.RI "union \fBdeviceErrors_t\fP"
.br
.RI "Represents the possible device error states\&. "
.ti -1c
.RI "struct \fBRadioStatus_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
