.TH "LoRaStats_t" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoRaStats_t \- Represents the LoRa Packet statistics\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OnethinxExt01\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint16_t \fBNbPktReceived\fP"
.br
.ti -1c
.RI "uint16_t \fBNbPktCrcErr\fP"
.br
.ti -1c
.RI "uint16_t \fBNbPktHeaderErr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents the LoRa Packet statistics\&. 
.SH "Field Documentation"
.PP 
.SS "uint16_t NbPktCrcErr"

.SS "uint16_t NbPktHeaderErr"

.SS "uint16_t NbPktReceived"


.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
