.TH "LoRaModulationParams_t" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
LoRaModulationParams_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OnethinxExt01\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBRadioLoRaSpreadingFactors_e\fP \fBSF\fP: 8"
.br
.ti -1c
.RI "\fBRadioLoRaBandwidths_e\fP \fBBW\fP: 8"
.br
.ti -1c
.RI "\fBRadioLoRaCodingRates_e\fP \fBCR\fP: 8"
.br
.ti -1c
.RI "\fBRadioLoraLowDataRateOptimize_e\fP \fBLowDataRateOptimize\fP: 8"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBRadioLoRaBandwidths_e\fP BW"

.SS "\fBRadioLoRaCodingRates_e\fP CR"

.SS "\fBRadioLoraLowDataRateOptimize_e\fP LowDataRateOptimize"

.SS "\fBRadioLoRaSpreadingFactors_e\fP SF"


.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
