.TH "lorawan_structs" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lorawan_structs \- Data Structures
.PP
 \- Onethinx LoRaWAN API Data Structures\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBStoredKeys_t\fP"
.br
.ti -1c
.RI "struct \fBOTAA_10x_t\fP"
.br
.ti -1c
.RI "struct \fBOTAA_11x_t\fP"
.br
.ti -1c
.RI "struct \fBABP_10x_t\fP"
.br
.ti -1c
.RI "struct \fBLoRaWAN_keys_t\fP"
.br
.ti -1c
.RI "union \fBcoreConfiguration_t\fP"
.br
.ti -1c
.RI "union \fBparameterStatus_t\fP"
.br
.ti -1c
.RI "union \fBradioStatus_t\fP"
.br
.ti -1c
.RI "union \fBmacStatus_t\fP"
.br
.ti -1c
.RI "union \fBsystemStatus_t\fP"
.br
.ti -1c
.RI "struct \fBcoreStatus_t\fP"
.br
.ti -1c
.RI "union \fBerrorStatus_t\fP"
.br
.ti -1c
.RI "union \fBdateTime_t\fP"
.br
.ti -1c
.RI "struct \fBwakeUpPin_t\fP"
.br
.ti -1c
.RI "struct \fBwakeUpTime_t\fP"
.br
.ti -1c
.RI "struct \fBsleepConfig_t\fP"
.br
.RI "Sleep configuration 
.br
 "
.ti -1c
.RI "struct \fBcoreInfo_t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Onethinx LoRaWAN API Data Structures\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
