.TH "lora_enums_general" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lora_enums_general \- General
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBRadioPacketTypes_e\fP { \fBPACKET_TYPE_GFSK\fP = 0x00, \fBPACKET_TYPE_LORA\fP = 0x01, \fBPACKET_TYPE_NONE\fP = 0x0F }"
.br
.RI "Represents the possible packet type (i\&.e\&. modem) used\&. "
.ti -1c
.RI "enum \fBRadioLoRaBandwidths_e\fP { \fBLORA_BW_500\fP = 6, \fBLORA_BW_250\fP = 5, \fBLORA_BW_125\fP = 4, \fBLORA_BW_062\fP = 3, \fBLORA_BW_041\fP = 10, \fBLORA_BW_031\fP = 2, \fBLORA_BW_020\fP = 9, \fBLORA_BW_015\fP = 1, \fBLORA_BW_010\fP = 8, \fBLORA_BW_007\fP = 0 }"
.br
.RI "Represents the bandwidth values for LoRa packet type\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBRadioLoRaBandwidths_e\fP"

.PP
Represents the bandwidth values for LoRa packet type\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILORA_BW_500 \fP\fP
.TP
\fB\fILORA_BW_250 \fP\fP
.TP
\fB\fILORA_BW_125 \fP\fP
.TP
\fB\fILORA_BW_062 \fP\fP
.TP
\fB\fILORA_BW_041 \fP\fP
.TP
\fB\fILORA_BW_031 \fP\fP
.TP
\fB\fILORA_BW_020 \fP\fP
.TP
\fB\fILORA_BW_015 \fP\fP
.TP
\fB\fILORA_BW_010 \fP\fP
.TP
\fB\fILORA_BW_007 \fP\fP
.SS "enum \fBRadioPacketTypes_e\fP"

.PP
Represents the possible packet type (i\&.e\&. modem) used\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPACKET_TYPE_GFSK \fP\fP
.TP
\fB\fIPACKET_TYPE_LORA \fP\fP
.TP
\fB\fIPACKET_TYPE_NONE \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
