.TH "parameterStatus_t" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
parameterStatus_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OnethinxCore01\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBparamErrors_e\fP \fBerrorStatus\fP: 8"
.br
.RI "Parameter Errors\&. "
.ti -1c
.RI "   uint8_t \fB__pad0__\fP: 8"
.br
.RI "reserved "
.ti -1c
.RI "}; "
.br
.ti -1c
.RI "uint8_t \fBreserved\fP [16]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct { \&.\&.\&. } "

.SS "uint8_t __pad0__"

.PP
reserved 
.SS "\fBparamErrors_e\fP errorStatus"

.PP
Parameter Errors\&. 
.SS "uint8_t reserved[16]"


.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
