.TH "RadioStatus_t" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RadioStatus_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OnethinxExt01\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBchipStatus_t\fP \fBchipStatus\fP"
.br
.RI "The device error states\&. "
.ti -1c
.RI "\fBIRQstatus_t\fP \fBIRQstatus\fP"
.br
.RI "The IRQ states\&. "
.ti -1c
.RI "\fBdeviceErrors_t\fP \fBdeviceErrors\fP"
.br
.RI "The device error states\&. "
.ti -1c
.RI "\fBLoRaPacketStatus_t\fP \fBLoRaPacketStatus\fP"
.br
.RI "The packet status for every packet type\&. "
.ti -1c
.RI "\fBLoRaStats_t\fP \fBLoRaStats\fP"
.br
.RI "The LoRa Packet statistics\&. "
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBchipStatus_t\fP chipStatus"

.PP
The device error states\&. 
.SS "\fBdeviceErrors_t\fP deviceErrors"

.PP
The device error states\&. 
.SS "\fBIRQstatus_t\fP IRQstatus"

.PP
The IRQ states\&. 
.SS "\fBLoRaPacketStatus_t\fP LoRaPacketStatus"

.PP
The packet status for every packet type\&. 
.SS "\fBLoRaStats_t\fP LoRaStats"

.PP
The LoRa Packet statistics\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
