.TH "StoredKeys_t" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StoredKeys_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OnethinxCore01\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBkeyType_e\fP \fBKeyType\fP"
.br
.ti -1c
.RI "uint8_t \fBKeyIndex\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint8_t KeyIndex"

.SS "\fBkeyType_e\fP KeyType"


.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
