.TH "structs_lorawan" 3 "Mon Jun 7 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
structs_lorawan \- Data Structures
.PP
 \- Onethinx LoRaWAN API Data Structures\&.  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBStoredKeys_t\fP"
.br
.RI "
.br
 "
.ti -1c
.RI "union \fBparameterStatus_t\fP"
.br
.RI "Parameter status structure returned by LoRaWAN functions, found in \fBcoreStatus_t\fP structure\&. "
.ti -1c
.RI "struct \fBsleepConfig_t\fP"
.br
.RI "Sleep configuration 
.br
 "
.ti -1c
.RI "struct \fBcoreInfo_t\fP"
.br
.ti -1c
.RI "union \fBcoreConfiguration_t\fP"
.br
.RI "The main LoRaWAN configuration structure, the location of which is forwarded to the stack\&. "
.in -1c
.SH "Detailed Description"
.PP 
Onethinx LoRaWAN API Data Structures\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
