.TH "wakeUpPin_t" 3 "Wed Jun 9 2021" "Onethinx LoRaWAN module" \" -*- nroff -*-
.ad l
.nh
.SH NAME
wakeUpPin_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <OnethinxCore01\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "bool \fBenabled\fP: 1"
.br
.ti -1c
.RI "bool \fBrisingEdge\fP: 1"
.br
.ti -1c
.RI "bool \fBinternalPullUpDown\fP: 1"
.br
.ti -1c
.RI "uint32_t \fB__pad0__\fP: 21"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "uint32_t __pad0__"

.SS "bool enabled"

.SS "bool internalPullUpDown"

.SS "bool risingEdge"


.SH "Author"
.PP 
Generated automatically by Doxygen for Onethinx LoRaWAN module from the source code\&.
